import assert from "node:assert/strict";
import test from "node:test";
import { chromium } from "playwright";

const baseURL=process.env.PLAYWRIGHT_BASE_URL??"http://127.0.0.1:3001";
async function freshPage(browser,viewport={width:1440,height:900}){const context=await browser.newContext({viewport});const page=await context.newPage();page.setDefaultTimeout(6000);await page.goto(`${baseURL}/creer`);await page.evaluate(()=>sessionStorage.clear());await page.reload();return page}
async function select(page,label){await page.getByRole("button",{name:label,exact:true}).click();await page.getByRole("button",{name:"Continuer",exact:true}).click()}
async function complete(page){await select(page,"Le coucher");await page.getByLabel("Prénom de l’enfant").fill("Éléonore");await page.getByRole("button",{name:"6 ans"}).click();await page.getByRole("button",{name:"Continuer",exact:true}).click();await select(page,"Les animaux");await select(page,"Un renard");await select(page,"Le rassurer");await page.getByRole("button",{name:"Doux et rassurant"}).click();await page.getByRole("button",{name:"Voir le récapitulatif"}).click();}

test("questionnaire: six étapes, persistance et récapitulatif",async()=>{const browser=await chromium.launch({headless:true});try{const page=await freshPage(browser);await assert.doesNotReject(()=>page.getByRole("heading",{name:"Quel moment vit votre enfant ?"}).waitFor());assert.equal(await page.getByRole("textbox").count(),0,"Aucun champ texte à l’étape 1");await select(page,"Le coucher");const input=page.getByLabel("Prénom de l’enfant");await input.fill("Jean-Baptiste");await page.getByRole("button",{name:"7 ans"}).click();await page.reload();await assert.doesNotReject(()=>page.getByRole("heading",{name:"Quel moment vit votre enfant ?"}).waitFor());await select(page,"Le coucher");const resetInput=page.getByLabel("Prénom de l’enfant");await resetInput.fill("Jean-Baptiste");await page.getByRole("button",{name:"7 ans"}).click();await page.getByRole("button",{name:"Continuer",exact:true}).click();await select(page,"L’espace");await select(page,"Une étoile");await select(page,"Lui donner du courage");await page.getByRole("button",{name:"Une petite aventure"}).click();await page.getByRole("button",{name:"Voir le récapitulatif"}).click();await assert.doesNotReject(()=>page.getByRole("heading",{name:/Tout est prêt/}).waitFor());assert.equal(await page.getByRole("textbox").count(),0,"Aucun champ libre au récapitulatif");assert.equal(await page.getByText("Jean-Baptiste · 7 ans").count(),1);}finally{await browser.close()}});

test("aucune génération avant le CTA d’aperçu",async()=>{const browser=await chromium.launch({headless:true});try{const page=await freshPage(browser);const generationRequests=[];page.on("request",request=>{if(/\/api\/stories\/.+\/preview|generativelanguage/i.test(request.url()))generationRequests.push(request.url())});await complete(page);assert.equal(generationRequests.length,0);await page.route("**/api/stories",route=>route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({id:"test-story"})}));await page.route("**/api/stories/test-story/preview",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({id:"test-story",status:"preview_ready"})}));await page.getByRole("button",{name:"Créer mon aperçu gratuit"}).click();await page.waitForURL(/\/livre\/test-story/);assert.equal(generationRequests.filter(url=>url.includes("/preview")).length,1);}finally{await browser.close()}});

test("mobile 375: navigation, CTA et absence de débordement",async()=>{const browser=await chromium.launch({headless:true});try{const page=await freshPage(browser,{width:375,height:812});await page.getByRole("button",{name:"Continuer",exact:true}).click();await assert.doesNotReject(()=>page.getByText("Choisissez une réponse pour continuer.").waitFor());await select(page,"Le coucher");await page.getByLabel("Prénom de l’enfant").fill("Mia");await page.getByRole("button",{name:"3 ans"}).click();const dimensions=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(dimensions.document<=dimensions.viewport,JSON.stringify(dimensions));const cta=await page.getByRole("button",{name:"Continuer",exact:true}).boundingBox();assert.ok(cta&&cta.y+cta.height<=812,"CTA visible dans le viewport");}finally{await browser.close()}});
